<?xml version="1.0"?>
<package format="2">
  <name>plan_manage</name>
  <version>0.0.0</version>
  <description>The plan_manage package</description>

  <maintainer email="nqq0915@163.com">nqq</maintainer>
  <license>TODO</license>

  <buildtool_depend>catkin</buildtool_depend>

  <depend>roscpp</depend>
  <depend>std_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>tf</depend>
  <depend>geometry_msgs</depend>
  <depend>gazebo_msgs</depend>

  <depend>onboard_detector</depend>
  <depend>plan_env</depend>
  <depend>path_searching</depend>
  <depend>bspline</depend>
  <depend>bspline_opt</depend>

  <build_depend>message_runtime</build_depend>
  <exec_depend>message_runtime</exec_depend>
  <exec_depend>xacro</exec_depend>

  <export>
    </export>
</package>